In [ ]:
import pandas as pd

In [ ]:
customer = pd.read_csv("customers_raw.csv")
marketing = pd.read_csv("marketing_raw.csv")
order_item = pd.read_csv("order_items_raw.csv")
order = pd.read_csv("orders_raw.csv")
product = pd.read_csv("products_raw.csv")
returns  = pd.read_csv("returns_raw.csv")

In [ ]:
print("customers :",customer.shape)
print("marketing :",marketing.shape)
print("order_item :",order_item.shape)
print("order :",order.shape)
print("product :",product.shape)
print("returns :",returns.shape)

customers : (657, 8)
marketing : (24, 6)
order_item : (5963, 7)
order : (2412, 6)
product : (15, 5)
returns : (229, 5)

In [ ]:
# Understand the columns
print(customer.columns)
print(marketing.columns)
print(order_item.columns)
print(order.columns)
print(product.columns)
print(returns.columns)

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'signup_date', 'customer_segment'],
      dtype='object')
Index(['month', 'campaign', 'campaign_spend', 'impressions', 'clicks',
       'leads'],
      dtype='object')
Index(['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price',
       'discount_pct', 'marketing_spend'],
      dtype='object')
Index(['order_id', 'customer_id', 'order_date', 'channel', 'payment_method',
       'order_status'],
      dtype='object')
Index(['product_id', 'product_name', 'category', 'list_price', 'unit_cost'], dtype='object')
Index(['return_id', 'order_id', 'return_date', 'return_reason',
       'refund_status'],
      dtype='object')

In [ ]:
## Data Profiling
print(customer.info())
print(marketing.info())
print(order_item.info())
print(order.info())
print(product.info())
print(returns.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 657 entries, 0 to 656
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       657 non-null    int64
 1   customer_name     657 non-null    object
 2   gender            657 non-null    object
 3   age               649 non-null    float64
 4   city              657 non-null    object
 5   state             657 non-null    object
 6   signup_date       657 non-null    object
 7   customer_segment  644 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 41.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   month           24 non-null     object
 1   campaign        24 non-null     object
 2   campaign_spend  24 non-null     int64
 3   impressions     24 non-null     int64
 4   clicks          24 non-null     int64
 5   leads           24 non-null     int64
dtypes: int64(4), object(2)
memory usage: 1.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5963 entries, 0 to 5962
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    5963 non-null   int64
 1   order_id         5963 non-null   int64
 2   product_id       5963 non-null   object
 3   quantity         5963 non-null   int64
 4   unit_price       5963 non-null   float64
 5   discount_pct     5941 non-null   float64
 6   marketing_spend  5953 non-null   float64
dtypes: float64(3), int64(3), object(1)
memory usage: 326.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2412 entries, 0 to 2411
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        2412 non-null   int64
 1   customer_id     2412 non-null   int64
 2   order_date      2412 non-null   object
 3   channel         2412 non-null   object
 4   payment_method  2397 non-null   object
 5   order_status    2412 non-null   object
dtypes: int64(2), object(4)
memory usage: 113.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    15 non-null     object
 1   product_name  15 non-null     object
 2   category      15 non-null     object
 3   list_price    15 non-null     int64
 4   unit_cost     15 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 732.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      229 non-null    object
 1   order_id       229 non-null    int64
 2   return_date    229 non-null    object
 3   return_reason  224 non-null    object
 4   refund_status  229 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.1+ KB
None

In [ ]:
## Missing-value profiling
customer.isnull().sum()

customer_id          0
customer_name        0
gender               0
age                  8
city                 0
state                0
signup_date          0
customer_segment    13
dtype: int64

In [ ]:
marketing.isnull().sum()

month             0
campaign          0
campaign_spend    0
impressions       0
clicks            0
leads             0
dtype: int64

In [ ]:
order_item.isnull().sum()

order_item_id       0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_pct       22
marketing_spend    10
dtype: int64

In [ ]:
order.isnull().sum()

order_id           0
customer_id        0
order_date         0
channel            0
payment_method    15
order_status       0
dtype: int64

In [ ]:
product.isnull().sum()

product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64

In [ ]:
returns.isnull().sum()

return_id        0
order_id         0
return_date      0
return_reason    5
refund_status    0
dtype: int64

In [ ]:
## Duplicate Analysis
print("customer :",customer.duplicated().sum())
print("marketing :",marketing.duplicated().sum())
print("order_item :",order_item.duplicated().sum())
print("order :",order.duplicated().sum())
print("product :",product.duplicated().sum())
print("returns :",returns.duplicated().sum())

customer : 7
marketing : 0
order_item : 18
order : 12
product : 0
returns : 0

In [ ]:
print("customer_id :",customer['customer_id'].duplicated().sum())
print("product_id :",product["product_id"].duplicated().sum())
print("order_id :",order["order_id"].duplicated().sum())
print("order_items_id :",order_item["order_item_id"].duplicated().sum())
print("return_id :",returns["return_id"].duplicated().sum())

customer_id : 7
product_id : 0
order_id : 12
order_items_id : 18
return_id : 0

In [ ]:
## Inspect the actual duplicates
customer[
    customer["customer_id"].duplicated(keep=False)
].sort_values("customer_id")

,customer_id,customer_name,gender,age,city,state,signup_date,customer_segment
168,1169,Customer 1169,Female,58.0,Pune,Maharashtra,2024-08-20,Corporate
656,1169,Customer 1169,Female,58.0,Pune,Maharashtra,2024-08-20,Corporate
650,1187,Customer 1187,Female,26.0,Mumbai,Maharashtra,2024-08-19,Small Business
186,1187,Customer 1187,Female,26.0,Mumbai,Maharashtra,2024-08-19,Small Business
652,1336,Customer 1336,Female,45.0,Kolkata,West Bengal,2025-06-30,NaN
335,1336,Customer 1336,Female,45.0,Kolkata,West Bengal,2025-06-30,NaN
468,1469,Customer 1469,Female,21.0,Mumbai,Maharashtra,2023-11-12,Consumer
651,1469,Customer 1469,Female,21.0,Mumbai,Maharashtra,2023-11-12,Consumer
508,1509,Customer 1509,Male,22.0,Pune,Maharashtra,2024-06-03,Consumer
653,1509,Customer 1509,Male,22.0,Pune,Maharashtra,2024-06-03,Consumer
654,1591,Customer 1591,Female,27.0,Kolkata,West Bengal,2023-11-14,Consumer
590,1591,Customer 1591,Female,27.0,Kolkata,West Bengal,2023-11-14,Consumer
646,1647,Customer 1647,Male,26.0,Bengaluru,Karnataka,2024-07-02,Consumer
655,1647,Customer 1647,Male,26.0,Bengaluru,Karnataka,2024-07-02,Consumer

In [ ]:
order[
    order["order_id"].duplicated(keep=False)
].sort_values("order_id")

,order_id,customer_id,order_date,channel,payment_method,order_status
73,50074,1353,2025-09-14,Store,Credit Card,Cancelled
2405,50074,1353,2025-09-14,Store,Credit Card,Cancelled
2403,50172,1357,2025-09-05,Online,Debit Card,Delivered
171,50172,1357,2025-09-05,Online,Debit Card,Delivered
2411,50190,1269,2025-05-18,Online,UPI,Delivered
189,50190,1269,2025-05-18,Online,UPI,Delivered
2401,50202,1130,2025-11-27,Store,Net Banking,Delivered
201,50202,1130,2025-11-27,Store,Net Banking,Delivered
203,50204,1263,2025-04-08,Store,Net Banking,Delivered
2400,50204,1263,2025-04-08,Store,Net Banking,Delivered
612,50613,1133,2025-05-25,Marketplace,Cash,Delivered
2407,50613,1133,2025-05-25,Marketplace,Cash,Delivered
2408,50714,1063,2024-08-05,Online,Debit Card,Delivered
713,50714,1063,2024-08-05,Online,Debit Card,Delivered
770,50771,1577,2024-05-14,Online,Cash,Delivered
2409,50771,1577,2024-05-14,Online,Cash,Delivered
1039,51040,1486,2024-12-18,Online,Cash,Delivered
2404,51040,1486,2024-12-18,Online,Cash,Delivered
2402,51087,1367,2025-01-10,Store,UPI,Delivered
1086,51087,1367,2025-01-10,Store,UPI,Delivered
2406,51139,1113,2025-10-01,Online,Debit Card,Delivered
1138,51139,1113,2025-10-01,Online,Debit Card,Delivered
1892,51893,1039,2025-12-28,Online,Net Banking,Cancelled
2410,51893,1039,2025-12-28,Online,Net Banking,Cancelled

In [ ]:
order_item[
    order_item["order_item_id"].duplicated(keep=False)
].sort_values("order_item_id")

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,marketing_spend
86,87,50029,P015,2,2462.39,10.0,375.48
5950,87,50029,P015,2,2462.39,10.0,375.48
5956,638,50274,P008,4,6720.79,0.0,487.87
637,638,50274,P008,4,6720.79,0.0,487.87
851,852,50359,P007,2,12772.69,10.0,108.94
5954,852,50359,P007,2,12772.69,10.0,108.94
5946,1152,50479,P005,4,8384.33,5.0,183.68
1151,1152,50479,P005,4,8384.33,5.0,183.68
1197,1198,50496,P008,2,6723.88,15.0,901.85
5949,1198,50496,P008,2,6723.88,15.0,901.85
5953,1332,50551,P008,3,7596.11,0.0,500.09
1331,1332,50551,P008,3,7596.11,0.0,500.09
1403,1404,50580,P014,1,3944.60,20.0,1194.87
5961,1404,50580,P014,1,3944.60,20.0,1194.87
1818,1819,50752,P015,2,2543.08,20.0,610.55
5952,1819,50752,P015,2,2543.08,20.0,610.55
5955,2080,50855,P008,1,7410.74,10.0,1008.52
2079,2080,50855,P008,1,7410.74,10.0,1008.52
2116,2117,50870,P010,3,2580.07,10.0,480.34
5948,2117,50870,P010,3,2580.07,10.0,480.34
5959,2252,50921,P008,3,7424.63,10.0,522.83
2251,2252,50921,P008,3,7424.63,10.0,522.83
2861,2862,51159,P014,1,3626.34,25.0,867.12
5958,2862,51159,P014,1,3626.34,25.0,867.12
5951,2901,51177,P007,2,12929.50,25.0,802.58
2900,2901,51177,P007,2,12929.50,25.0,802.58
3555,3556,51445,P011,3,1290.37,0.0,687.96
5945,3556,51445,P011,3,1290.37,0.0,687.96
5947,4788,51934,P001,3,69511.21,5.0,1045.77
4787,4788,51934,P001,3,69511.21,5.0,1045.77
5334,5335,52149,P012,1,19790.41,25.0,823.09
5960,5335,52149,P012,1,19790.41,25.0,823.09
5474,5475,52210,P010,1,2535.27,20.0,955.25
5957,5475,52210,P010,1,2535.27,20.0,955.25
5839,5840,52358,P002,4,31100.00,0.0,966.12
5962,5840,52358,P002,4,31100.00,0.0,966.12

In [ ]:
## Categorical Value Consistency
## for cusstomer
print(customer["gender"].value_counts(dropna=False))
print(customer["city"].value_counts(dropna=False))
print(customer["state"].value_counts(dropna=False))
print(customer["customer_segment"].value_counts(dropna=False))

gender
Female    354
Male      303
Name: count, dtype: int64
city
Kolkata      90
Pune         85
Bengaluru    85
Mumbai       84
Chennai      79
Patna        78
Delhi        76
Hyderabad    70
delhi        10
Name: count, dtype: int64
state
Maharashtra    171
West Bengal     93
Karnataka       86
Tamil Nadu      81
Bihar           78
Delhi           77
Telangana       71
Name: count, dtype: int64
customer_segment
Consumer          417
Small Business    120
Corporate         107
NaN                13
Name: count, dtype: int64

In [ ]:
##for orders
print(order["channel"].value_counts(dropna=False))
print(order["payment_method"].value_counts(dropna=False))
print(order["order_status"].value_counts(dropna=False))

channel
Online         1438
Store           638
Marketplace     326
online           10
Name: count, dtype: int64
payment_method
Cash           502
Credit Card    494
Debit Card     470
Net Banking    469
UPI            462
NaN             15
Name: count, dtype: int64
order_status
Delivered    1984
Returned      229
Cancelled     199
Name: count, dtype: int64

In [ ]:
#for product
print(product["category"].value_counts(dropna=False))

category
Electronics    7
Accessories    4
Furniture      3
electronics    1
Name: count, dtype: int64

In [ ]:
## for returns
print(returns["return_reason"].value_counts(dropna=False))
print(returns["refund_status"].value_counts(dropna=False))

return_reason
Wrong Item       49
Late Delivery    47
Damaged          45
Quality Issue    43
Changed Mind     40
NaN               5
Name: count, dtype: int64
refund_status
Refunded    170
Pending      49
Rejected     10
Name: count, dtype: int64

In [ ]:
## Numeric data quality
customer["age"].describe()

count    649.000000
mean      42.354391
std       15.133689
min       18.000000
25%       30.000000
50%       41.000000
75%       56.000000
max       69.000000
Name: age, dtype: float64

In [ ]:
order_item[["quantity", "unit_price", "discount_pct", "marketing_spend"]].describe()

          quantity    unit_price  discount_pct  marketing_spend
count  5963.000000   5963.000000   5941.000000      5953.000000
mean      2.515177  14057.227999     12.565225       605.216395
std       1.116899  16374.095810      8.551251       345.091363
min       0.000000   1260.560000      0.000000         0.510000
25%       2.000000   2947.345000      5.000000       302.680000
50%       3.000000   8510.560000     15.000000       614.690000
75%       4.000000  17067.610000     20.000000       905.100000
max       4.000000  71493.210000     25.000000      1199.980000

In [ ]:
product[["list_price", "unit_cost"]].describe()

         list_price     unit_cost
count     15.000000     15.000000
mean   13946.666667   9310.466667
std    16679.622583  12126.245585
min     1400.000000    672.000000
25%     3300.000000   1735.000000
50%     8500.000000   5100.000000
75%    16750.000000  10977.500000
max    65000.000000  46800.000000

In [ ]:
marketing[[
    "campaign_spend", "impressions", "clicks", "leads"
]].describe()

       campaign_spend    impressions        clicks       leads
count       24.000000      24.000000     24.000000    24.00000
mean    113575.500000  407167.250000  25600.166667  3731.50000
std      34530.179849  174320.857011  12087.540728  2094.37111
min      63894.000000  138075.000000   6181.000000   689.00000
25%      81182.250000  264866.750000  17173.750000  2458.00000
50%     114646.500000  463183.500000  25440.000000  3538.00000
75%     146209.500000  533310.250000  36175.000000  4811.00000
max     164938.000000  688978.000000  43728.000000  7995.00000

In [ ]:
order_item[order_item["quantity"]==0]

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,marketing_spend
788,789,50335,P008,0,7301.19,0.0,82.05
1256,1257,50519,P011,0,1481.07,5.0,796.09
1607,1608,50660,P001,0,69212.48,15.0,582.57
2218,2219,50908,P009,0,1990.07,15.0,650.01
2813,2814,51138,P014,0,4048.61,10.0,1164.86

In [ ]:
order_item["quantity"].value_counts().sort_index()

quantity
0       5
1    1454
2    1473
3    1526
4    1505
Name: count, dtype: int64

In [ ]:
## referencing integrity
order["customer_id"].isin(customer["customer_id"]).value_counts()

customer_id
True    2412
Name: count, dtype: int64

In [ ]:
order_item["order_id"].isin(order["order_id"]).value_counts()

order_id
True    5963
Name: count, dtype: int64

In [ ]:
order_item["product_id"].isin(product["product_id"]).value_counts()

product_id
True    5963
Name: count, dtype: int64

In [ ]:
returns["order_id"].isin(order["order_id"]).value_counts()

order_id
True    229
Name: count, dtype: int64

In [ ]:
## Preserve raw data
customer_clean = customer.copy()
order_clean = order.copy()
order_item_clean = order_item.copy()
product_clean = product.copy()
returns_clean = returns.copy()
marketing_clean = marketing.copy()

# Data Claening

In [ ]:
## check the clean data counts
customer_before = len(customer_clean)
order_before = len(order_clean)
order_item_before = len(order_item_clean)

In [ ]:
## remove exact duplicates
customer_clean = customer_clean.drop_duplicates()
order_clean = order_clean.drop_duplicates()
order_item_clean = order_item_clean.drop_duplicates()

In [ ]:
## Standardize categorical values

## for customer city
customer_clean["city"] = customer_clean["city"].replace({"delhi":"Delhi"})

In [ ]:
## for order channel
order_clean["channel"] = order_clean["channel"].replace({"online":"Online"})

In [ ]:
## for product
product_clean["category"] = product_clean["category"].replace({"electronics":"Electronics"})

In [ ]:
product_clean["category"].value_counts(dropna=False)

category
Electronics    8
Accessories    4
Furniture      3
Name: count, dtype: int64

In [ ]:
## remove unwanted spaces
## for customer

customer_clean["gender"] = customer_clean["gender"].str.strip()
customer_clean["city"] = customer_clean["city"].str.strip()
customer_clean["state"] = customer_clean["state"].str.strip()
customer_clean["customer_segment"] = customer_clean["customer_segment"].str.strip()

In [ ]:
## for order
order_clean["channel"] = order_clean["channel"].str.strip()
order_clean["payment_method"] = order_clean["payment_method"].str.strip()
order_clean["order_status"] = order_clean["order_status"].str.strip()

In [ ]:
## for product
product_clean["product_name"] = product_clean["product_name"].str.strip()
product_clean["category"] = product_clean["category"].str.strip()

In [ ]:
## missing-value treatment.
## check whose are fit mean vs meadian

print(customer_clean["age"].describe())

count    642.000000
mean      42.465732
std       15.118345
min       18.000000
25%       30.000000
50%       41.000000
75%       56.000000
max       69.000000
Name: age, dtype: float64

In [ ]:
## check distribution of age
customer_clean["age"].value_counts().sort_index()

age
18.0    16
19.0    12
20.0    12
21.0    10
22.0    12
23.0    18
24.0    14
25.0    14
26.0    15
27.0    15
28.0    10
29.0     9
30.0    18
31.0    16
32.0     8
33.0    18
34.0    14
35.0    14
36.0    14
37.0     9
38.0    14
39.0    16
40.0     9
41.0    16
42.0    11
43.0    11
44.0    11
45.0    18
46.0    11
47.0    11
48.0    14
49.0    10
50.0    10
51.0    11
52.0     6
53.0    10
54.0    10
55.0    10
56.0    14
57.0     9
58.0    14
59.0     8
60.0     7
61.0     7
62.0    20
63.0    14
64.0    16
65.0    10
66.0    12
67.0    12
68.0     9
69.0    13
Name: count, dtype: int64

In [ ]:
## age convert into integer data type
customer_clean["age"] = customer_clean["age"].astype(int)

In [ ]:
## fill age with median
customer_clean["age"] = customer_clean["age"].fillna(customer_clean["age"].median())

In [ ]:
## check the missing values
customer_clean["age"].isnull().sum()

np.int64(0)

In [ ]:
## check the customer segment

customer_clean["customer_segment"].value_counts(dropna=False)

customer_segment
Consumer          413
Small Business    119
Corporate         106
NaN                12
Name: count, dtype: int64

In [ ]:
## fill with the unknown values
customer_clean["customer_segment"] = customer_clean["customer_segment"].fillna("Unknown")

In [ ]:
## verify the data
customer_clean["customer_segment"].value_counts(dropna=False)

customer_segment
Consumer          413
Small Business    119
Corporate         106
Unknown            12
Name: count, dtype: int64

In [ ]:
customer_clean["customer_segment"].isnull().sum()

np.int64(0)

In [ ]:
## for payment method fill with unknown data
order_clean["payment_method"] = order_clean["payment_method"].fillna("Unknown")

In [ ]:
## verify
print(order_clean["payment_method"].value_counts(dropna=False))
print(order_clean["payment_method"].isnull().sum())

payment_method
Cash           499
Credit Card    493
Debit Card     467
Net Banking    466
UPI            460
Unknown         15
Name: count, dtype: int64
0

In [ ]:
## check marketing spend
print(order_item_clean["marketing_spend"].describe())
print(order_item_clean["marketing_spend"].isnull().sum())

count    5935.000000
mean      604.941919
std       345.191965
min         0.510000
25%       301.750000
50%       614.560000
75%       904.875000
max      1199.980000
Name: marketing_spend, dtype: float64
10

In [ ]:
## for return reason fill with unknown values
returns_clean["return_reason"] = returns_clean["return_reason"].fillna("Unknown")

In [ ]:
## verify the return reason
returns_clean["return_reason"].value_counts(dropna=False)

return_reason
Wrong Item       49
Late Delivery    47
Damaged          45
Quality Issue    43
Changed Mind     40
Unknown           5
Name: count, dtype: int64

# Data Type Convert

In [ ]:
## convert signup date columns into date type
customer_clean["signup_date"] = pd.to_datetime(customer_clean["signup_date"])

In [ ]:
#verify
customer_clean["signup_date"].dtype

dtype('<M8[ns]')

In [ ]:
## convert order date into date type
order_clean["order_date"] = pd.to_datetime(order_clean["order_date"])

In [ ]:
## verify
order_clean["order_date"].dtype

dtype('<M8[ns]')

In [ ]:
## convert return date into date type
returns_clean["return_date"] = pd.to_datetime(returns_clean["return_date"])

In [ ]:
## verify
returns_clean["return_date"].dtype

dtype('<M8[ns]')

In [ ]:
## month date into date type
marketing_clean["month"] = pd.to_datetime(marketing_clean["month"])

In [ ]:
## verify
marketing_clean["month"].dtype

dtype('<M8[ns]')

In [ ]:
## Check quantity
order_item_clean["quantity"].value_counts().sort_index()

quantity
0       5
1    1449
2    1468
3    1521
4    1502
Name: count, dtype: int64

In [ ]:
order_item_clean["quantity"].describe()

count    5945.000000
mean        2.515728
std         1.117039
min         0.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: quantity, dtype: float64

In [ ]:
order_item_clean[
    order_item_clean["quantity"]<=0
]

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,marketing_spend
788,789,50335,P008,0,7301.19,0.0,82.05
1256,1257,50519,P011,0,1481.07,5.0,796.09
1607,1608,50660,P001,0,69212.48,15.0,582.57
2218,2219,50908,P009,0,1990.07,15.0,650.01
2813,2814,51138,P014,0,4048.61,10.0,1164.86

In [ ]:
## remove invalid data from quantity
order_item_clean = order_item_clean[
    order_item_clean["quantity"]>0
].copy()

In [ ]:
## Check unit_price
order_item_clean["unit_price"].describe()

count     5940.000000
mean     14062.267800
std      16364.313862
min       1260.560000
25%       2949.362500
50%       8527.025000
75%      17082.877500
max      71493.210000
Name: unit_price, dtype: float64

In [ ]:
order_item_clean[
    order_item_clean["unit_price"]<=0
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_pct, marketing_spend]
Index: []

In [ ]:
## Check product prices and costs
product_clean[["list_price", "unit_cost"]].describe()

         list_price     unit_cost
count     15.000000     15.000000
mean   13946.666667   9310.466667
std    16679.622583  12126.245585
min     1400.000000    672.000000
25%     3300.000000   1735.000000
50%     8500.000000   5100.000000
75%    16750.000000  10977.500000
max    65000.000000  46800.000000

In [ ]:
product_clean[
    (product_clean["list_price"]<=0)|
    (product_clean["unit_cost"]<=0)
]

Empty DataFrame
Columns: [product_id, product_name, category, list_price, unit_cost]
Index: []

In [ ]:
product_clean[
    product_clean["unit_cost"]>=product_clean["list_price"]
]

Empty DataFrame
Columns: [product_id, product_name, category, list_price, unit_cost]
Index: []

In [ ]:
## validate discounts
order_item_clean[
    (order_item_clean["discount_pct"]<0)|
    (order_item_clean["discount_pct"]>100)
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_pct, marketing_spend]
Index: []

In [ ]:
## check marketing_spend:
order_item_clean[order_item_clean["marketing_spend"]<0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_pct, marketing_spend]
Index: []

# Check Final Data Validation

In [ ]:
print("Customer:", customer_clean.shape)
print("Marketing:", marketing_clean.shape)
print("Order Item:", order_item_clean.shape)
print("Order:", order_clean.shape)
print("Product:", product_clean.shape)
print("Returns:", returns_clean.shape)

Customer: (650, 8)
Marketing: (24, 6)
Order Item: (5940, 7)
Order: (2400, 6)
Product: (15, 5)
Returns: (229, 5)

In [ ]:
print(customer_clean.isnull().sum())
print(order_clean.isnull().sum())
print(order_item_clean.isnull().sum())
print(product_clean.isnull().sum())
print(returns_clean.isnull().sum())
print(marketing_clean.isnull().sum())

customer_id         0
customer_name       0
gender              0
age                 0
city                0
state               0
signup_date         0
customer_segment    0
dtype: int64
order_id          0
customer_id       0
order_date        0
channel           0
payment_method    0
order_status      0
dtype: int64
order_item_id       0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_pct       22
marketing_spend    10
dtype: int64
product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64
return_id        0
order_id         0
return_date      0
return_reason    0
refund_status    0
dtype: int64
month             0
campaign          0
campaign_spend    0
impressions       0
clicks            0
leads             0
dtype: int64

In [ ]:
print("Customer duplicates:", customer_clean.duplicated().sum())
print("Order duplicates:", order_clean.duplicated().sum())
print("Order Item duplicates:", order_item_clean.duplicated().sum())
print("Product duplicates:", product_clean.duplicated().sum())
print("Returns duplicates:", returns_clean.duplicated().sum())
print("Marketing duplicates:", marketing_clean.duplicated().sum())

Customer duplicates: 0
Order duplicates: 0
Order Item duplicates: 0
Product duplicates: 0
Returns duplicates: 0
Marketing duplicates: 0

In [ ]:
customer_clean.info()
order_clean.info()
order_item_clean.info()
product_clean.info()
returns_clean.info()
marketing_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 650 entries, 0 to 649
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       650 non-null    int64
 1   customer_name     650 non-null    object
 2   gender            650 non-null    object
 3   age               650 non-null    float64
 4   city              650 non-null    object
 5   state             650 non-null    object
 6   signup_date       650 non-null    datetime64[ns]
 7   customer_segment  650 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 45.7+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 2400 entries, 0 to 2399
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        2400 non-null   int64
 1   customer_id     2400 non-null   int64
 2   order_date      2400 non-null   datetime64[ns]
 3   channel         2400 non-null   object
 4   payment_method  2400 non-null   object
 5   order_status    2400 non-null   object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 131.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 5940 entries, 0 to 5944
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    5940 non-null   int64
 1   order_id         5940 non-null   int64
 2   product_id       5940 non-null   object
 3   quantity         5940 non-null   int64
 4   unit_price       5940 non-null   float64
 5   discount_pct     5918 non-null   float64
 6   marketing_spend  5930 non-null   float64
dtypes: float64(3), int64(3), object(1)
memory usage: 371.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    15 non-null     object
 1   product_name  15 non-null     object
 2   category      15 non-null     object
 3   list_price    15 non-null     int64
 4   unit_cost     15 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 732.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      229 non-null    object
 1   order_id       229 non-null    int64
 2   return_date    229 non-null    datetime64[ns]
 3   return_reason  229 non-null    object
 4   refund_status  229 non-null    object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 9.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   month           24 non-null     datetime64[ns]
 1   campaign        24 non-null     object
 2   campaign_spend  24 non-null     int64
 3   impressions     24 non-null     int64
 4   clicks          24 non-null     int64
 5   leads           24 non-null     int64
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 1.3+ KB

# Export Cleaned Datasets

In [ ]:
customer_clean.to_csv("customer_clean.csv", index=False)
order_clean.to_csv("order_clean.csv", index=False)
order_item_clean.to_csv("order_item_clean.csv", index=False)
product_clean.to_csv("product_clean.csv", index=False)
marketing_clean.to_csv("marketing_clean.csv", index=False)
returns_clean.to_csv("returns_clean.csv", index=False)

In [ ]:
## check the save files
!ls

customer_clean.csv   order_clean.csv	   product_clean.csv  sample_data
customers_raw.csv    order_item_clean.csv  products_raw.csv
marketing_clean.csv  order_items_raw.csv   returns_clean.csv
marketing_raw.csv    orders_raw.csv	   returns_raw.csv

In [ ]:
## download all files in as zip
!zip clean_retail_data.zip customer_clean.csv marketing_clean.csv order_item_clean.csv order_clean.csv product_clean.csv returns_clean.csv

from google.colab import files
files.download("clean_retail_data.zip")

  adding: customer_clean.csv (deflated 82%)
  adding: marketing_clean.csv (deflated 59%)
  adding: order_item_clean.csv (deflated 63%)
  adding: order_clean.csv (deflated 81%)
  adding: product_clean.csv (deflated 49%)
  adding: returns_clean.csv (deflated 77%)